### ISSUE TITLE
Is it possible to output the YAML file after these replacements?

### ISSUE THREAD

**Issue by matsui-kento** [zoncoen/scenarigo#404]
I recently started using scenarigo. 

It seems that scenarigo internally replaces YAML files. 
Is it possible to output the YAML file after these replacements have been made?
I know that I can use "scenarigo dump" to output the YAML file before replacement.

**Comment by zoncoen** [comment]
Thank you for using Scenarigo.
What is the "replacement" you said? If it means embedded variables by template string, it is difficult to know the results before running. Scenarigo resolves templates at runtime.

**Comment by matsui-kento** [comment]
Thank you for your reply.
"replacement" means after execute.
For example, I wanted the YAML after `{{ vars.url }}` and `{{ plugins.uuid.New() }}` were replaced with the actual values ​​by execute.
I read the code and found that there is no such functionality.

**Comment by zoncoen** [comment]
As mentioned above, some results of template strings can change according to the runtime contexts. For example, the result of this expression depends on the actual response body. In this way, **we can't get all the results beforehand without test execution**. Therefore, Scenarigo doesn't provide the feature you mentioned.

Scenarigo dumps the actual request and response in default when the step fails. Please use it to know the actual values used to send requests. If you always want to get the actual request and response, use `--verbose` option or enable `verbose` in the configuration `.scenarigo.yaml`.

**Comment by zoncoen** [comment]
If you have further questions, feel free to reopen this issue.
